import requests
from twilio.rest import Client

SID = "YOUR SID FROM TWILIO ACCOUNT"
AUTH = "YOUR AUTH FROM TWILIO ACCOUNT"
twilio_number = "+YOUR TEMPORARY NUMBER GENERATED BY TWILION"
API = "OPEN WATHER API WITH YOUR KEY AND PROPER PRARAMETER"

api = requests.get(API)
api.raise_for_status()
data = api.json()
count = 0
for item in data["list"]:
    hour = item["weather"][0]["id"]
    count+=1
    if hour < 700:

        client = Client(SID, AUTH)
        message = client.messages.create(
            body=f'Ahoy 👋...TYPE A MSG YOU WANT TO SENT HERE',
            messaging_service_sid='YOUR MSSID GENERATED BY TWILIO',
            to='WRITE A NUMBER HERE ON WHICH YOU WANT TO SENT A MSG HERE'
        )
        print(message.status)









